#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server web-01 54.196.196.104 check
   server web-02 18.207.142.94 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
