#!/usr/bin/env bash
# Bash script to ping an IP address

# Check if the script is run with the correct number of arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the command line argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 "$ip_address"
