#!/usr/bin/env bash
# Script: fizzbuzz.sh
# Description: Display numbers from 1 to 100 with Fizz, Buzz, or FizzBuzz conditions.

for ((i=1; i<=100; i++)); do
    if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
