#!/usr/bin/env bash
# Script: apache_log_parser.sh
# Description: Display visitor IP along with HTTP status code from Apache log file.

# Apache log file path
log_file="apache-access.log"

# Check if the log file exists
if [ -e "$log_file" ]; then

    # Use awk to extract and display IP and HTTP status code
    awk '{print $1, $9}' "$log_file"

else
    echo "Error: $log_file does not exist."
fi
