#!/usr/bin/env bash
# Script to display "Best School" 10 times using a while loop

# Initialize a counter
counter=1

# Using a while loop to iterate 10 times
while [ $counter -le 10 ]; do
    echo "Best School"
    ((counter++))
done
