#!/usr/bin/env bash
# Script to display "Best School" 10 times, with a special case on the 9th iteration

# Initialize a counter
counter=1

# Using a while loop to iterate 10 times
while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((counter++))
done
