#!/usr/bin/env bash
# Script to display numbers from 1 to 20 with specific messages for certain iterations

# Initialize a counter
counter=1

# Using a while loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "4 and then bad luck from China"
            ;;
        9)
            echo "9 and then bad luck from Japan"
            ;;
        17)
            echo "17 and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
